### PR TITLE
Update LigerShark.WebOptimizer.Core to version 3.0.403

### PR DESCRIPTION
**Pull request by lahma**
With the latest changes to Core and tweaks to SASS I think a new release of this projects would be a great addition, if you have the time and willingness to do another release after this PR 🙏🏻

### CODE REVIEW

**Comment by lahma** [comment]
And why I'm being such an PITA? Some license checkers flag unknown licenses so I thought maybe tweaking a bit and contributing back a little would make sense again. Thank you for maintaining this library!

**Comment by Taritsyn** [comment]
In the next 2 hours, I plan to send a PR fixing the [“Concurrency issue when initializing JS engine switcher in startup”](https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/115) error. Therefore, do not rush to publish a new release yet.

**Comment by lahma** [comment]
Hey thanks for chiming in @Taritsyn , you're now also a PITA 😉 Great to see things getting together this way, it was my colleague reporting the issue you have fixed ❤️

**Comment by lahma** [comment]
OK this seems now redundant with new release on NuGet and I can always mix and match versions.

**Pull request closed without merging**
